# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/design/form_discharge_of_patients.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_patient = QtWidgets.QComboBox(self.centralwidget)
        self.name_patient.setGeometry(QtCore.QRect(20, 80, 410, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name_patient.setFont(font)
        self.name_patient.setMaxVisibleItems(15)
        self.name_patient.setObjectName("name_patient")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 230, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.choice_date = QtWidgets.QCalendarWidget(self.centralwidget)
        self.choice_date.setGeometry(QtCore.QRect(20, 170, 410, 301))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.choice_date.setFont(font)
        self.choice_date.setObjectName("choice_date")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 180, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.button_discharge = QtWidgets.QPushButton(self.centralwidget)
        self.button_discharge.setGeometry(QtCore.QRect(260, 120, 170, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.button_discharge.setFont(font)
        self.button_discharge.setObjectName("button_discharge")
        self.search = QtWidgets.QLineEdit(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(20, 50, 410, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.search.setFont(font)
        self.search.setObjectName("search")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(260, 5, 170, 35))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выписка пациента"))
        self.label_4.setText(_translate("MainWindow", "ФИО пациента:"))
        self.label_5.setText(_translate("MainWindow", "Дата выписки:"))
        self.button_discharge.setText(_translate("MainWindow", "Выписать"))
        self.cancel_button.setText(_translate("MainWindow", "Отмена"))
