# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/design/form_adding_procedures_one.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_table = QtWidgets.QTableWidget(self.centralwidget)
        self.main_table.setGeometry(QtCore.QRect(10, 110, 700, 370))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_table.setFont(font)
        self.main_table.setRowCount(0)
        self.main_table.setColumnCount(2)
        self.main_table.setObjectName("main_table")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(10, 10, 130, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.add_new_procedure_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_new_procedure_button.setGeometry(QtCore.QRect(10, 60, 290, 40))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.add_new_procedure_button.setFont(font)
        self.add_new_procedure_button.setStyleSheet("background: #C7FE80;")
        self.add_new_procedure_button.setObjectName("add_new_procedure_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit_button.setText(_translate("MainWindow", "Вернуться"))
        self.add_new_procedure_button.setText(_translate("MainWindow", "Добавить процедуру +"))
